
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduQuest - Online Learning Platform</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            color: #333;
        }
        .navbar {
            position: fixed;
            top: 0;
            width: 100%;
            background-color: #333;
            color: #fff;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .navbar a {
            color: #fff;
            text-decoration: none;
            padding: 10px;
        }
        .search-bar input {
            padding: 5px;
            border: none;
            border-radius: 5px;
        }
        .hero {
            position: relative;
            height: 100vh;
            background: url('placeholder-video.jpg') no-repeat center center/cover;
            color: #fff;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .hero h1 {
            font-size: 3em;
            margin: 0;
        }
        .hero button {
            background-color: #007bff;
            border: none;
            color: #fff;
            padding: 10px 20px;
            font-size: 1em;
            border-radius: 5px;
            cursor: pointer;
        }
        .courses, .learning-paths, .success-stories {
            padding: 40px 20px;
            text-align: center;
        }
        .courses .course-card {
            display: inline-block;
            width: 250px;
            margin: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 20px;
        }
        .footer {
            background-color: #f1f1f1;
            padding: 20px;
            text-align: center;
        }
        .footer a {
            margin: 0 10px;
            text-decoration: none;
            color: #333;
        }
        .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        }
        .modal-content {
            background: #fff;
            padding: 20px;
            border-radius: 5px;
            width: 400px;
        }
        .modal button {
            background-color: #007bff;
            border: none;
            color: #fff;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <div class="links">
            <a href="#math">Math</a>
            <a href="#science">Science</a>
            <a href="#languages">Languages</a>
            <a href="#arts">Arts</a>
        </div>
        <div class="search-bar">
            <input type="text" placeholder="Search courses...">
        </div>
    </div>

    <div class="hero">
        <h1 id="tagline">Learn at your own pace</h1>
        <button onclick="window.location.href='#courses'">Get Started</button>
    </div>

    <div class="courses" id="courses">
        <h2>Featured Courses</h2>
        <div class="course-card">
            <img src="placeholder-image.jpg" alt="Course Image" width="100%">
            <h3>Course Title</h3>
            <p>Instructor Name</p>
            <p>Course description goes here...</p>
        </div>
        <!-- Add more course cards as needed -->
    </div>

    <div class="learning-paths" id="learning-paths">
        <h2>Find Your Learning Path</h2>
        <button onclick="startQuiz()">Start Quiz</button>
    </div>

    <div class="success-stories" id="success-stories">
        <h2>Success Stories</h2>
        <p>"This platform changed my life!" - Student Name</p>
        <!-- Add more testimonials as needed -->
    </div>

    <div class="footer">
        <a href="#blog">Blog</a>
        <a href="#faq">FAQ</a>
        <a href="#privacy">Privacy Policy</a>
        <button onclick="openModal()">Contact Us</button>
    </div>

    <div class="modal" id="contactModal">
        <div class="modal-content">
            <h2>Contact Us</h2>
            <form>
                <label for="name">Name:</label><br>
                <input type="text" id="name" name="name"><br><br>
                <label for="email">Email:</label><br>
                <input type="email" id="email" name="email"><br><br>
                <label for="message">Message:</label><br>
                <textarea id="message" name="message"></textarea><br><br>
                <button type="submit">Send</button>
            </form>
        </div>
    </div>

    <script>
        const taglines = [
            "Learn at your own pace",
            "Discover new passions",
            "Expand your horizons"
        ];
        let taglineIndex = 0;
        const taglineElement = document.getElementById('tagline');

        function updateTagline() {
            taglineElement.textContent = taglines[taglineIndex];
            taglineIndex = (taglineIndex + 1) % taglines.length;
        }

        setInterval(updateTagline, 3000);

        function openModal() {
            document.getElementById('contactModal').style.display = 'flex';
        }

        window.onclick = function(event) {
            if (event.target == document.getElementById('contactModal')) {
                document.getElementById('contactModal').style.display = 'none';
            }
        }

        function startQuiz() {
            // Placeholder function for quiz
            alert('Quiz functionality not implemented yet.');
        }
    </script>
</body>
</html>
